
REVOKE ALL PRIVILEGES ON SCHEMA public FROM GROUP public;
REVOKE ALL PRIVILEGES ON DATABASE projectfree FROM GROUP public;

CREATE ROLE admin SUPERUSER;

DROP ROLE function;
CREATE ROLE function;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO function;

DROP ROLE insert;
CREATE ROLE insert;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO insert;
GRANT UPDATE ON ALL SEQUENCES IN SCHEMA public TO insert;

DROP ROLE retrieve;
CREATE ROLE retrieve;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO retrieve;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO retrieve;

DROP ROLE update;
CREATE ROLE update;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO update;

DROP ROLE delete;
CREATE ROLE delete;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO delete;

GRANT USAGE ON SCHEMA public TO insert, retrieve, update, delete, function;




