

CREATE OR REPLACE FUNCTION atriAtividade(id INTEGER)
RETURNS BOOLEAN AS $$
BEGIN
	UPDATE atividade SET fim_atividade = CURRENT_DATE WHERE id_atividade = id;
	RETURN FOUND;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION concluirAtividade(id INTEGER)
RETURNS BOOLEAN AS $$
BEGIN
	UPDATE atividade SET fim_atividade = CURRENT_DATE WHERE id_atividade = id;
	RETURN FOUND;
END;
$$ LANGUAGE PLPGSQL;
